name: Python CI/CD

on:
  workflow_call:

  push:
    branches:
      - main

env:
  SERVICE_NAME: ml-assets-prediction

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest tests/

      - name: Lint code
        run: pylint . --fail-on=E,unused-import  --fail-under=9.5

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERVICE_NAME }}
          path: .
